// Used for front page - Companies Hiring Through the Coalition
// and also used for /hiring-companies
export const companies = [
  "Microsoft",
  "Amazon",
  "CACI",
  "Washington State Department of Labor and Industries",
  "Kros-Wise",
  "Halvik",
  "Federal Aviation Administration",
  "Olympia Computer",
  "Linquest",
  "Lake County",
  "Leidos",
  "Washington State Department of Social and Health Services",
  "Washington State Department of Health",
  "Washington State National Guard",
  "Saint Martin's University",
  "Washington Technical Solutions",
  "Oracle",
  "Interfuze",
  "Vertex",
  "Zachary Piper",
  "Colorado State University System",
  "One Source PCS",
  "Tek Systems",
  "Fall River Health Services",
  "Bradken",
  "Sazerac",
  "New Orleans",
  "Astrion",
  "Lucky Eagle Casino",
  "EXP Technical",
  "SearchPro",
  "ABC Legal",
  "Graphium Health",
  "Costco IT",
  "PACCAR",
  "Allen Institute",
  "Chenega Agile Real-Time Solutions",
  "US Coast Guard",
  "Amazon Web Services",
  "Sound Transit",
  "Rover",
  "Smartsheet",
  "BetterTabs",
  "Ookla",
  "Salesforce",
  "SAP Concur",
  "Microsoft ST",
  "Snowflake",
  "Department of Defense",
  "Empire Control Systems",
  "NCW Libraries",
  "Key Methods",
  "CVCH",
  "AT&T",
  "Southwest Airlines Corporation",
  "TELUS International (CDA) Inc",
  "Chririsa DF LLC",
  "Catholic Health Initiatives",
  "Insight Global",
  "SBL Enterprises",
  "Northwest Center Services",
  "University of Maryland Global Campus",
  "TriNet Corp",
  "Costco",
  "SpaceX",
  "Aquent",
  "Blueprint Technologies",
  "Evergreen Medical Center",
  "H10 Capital",
  "UW Medicine",
  "Davis Wright Tremaine LLP",
  "BECU",
  "General Datatech",
  "L.P. (GDT)",
  "Washington State Housing Finance Commission",
  "Meta",
  "Fungi Perfecti",
  "Kforce",
  "Experis US Inc",
  "TEAMSOS",
  "Seattle Children's Hospital",
  "YUPRO",
  "McKinstry",
  "Securitas",
  "King County Information Technology (KCIT)",
  "Expeditors",
  "Expedia Group",
  "Boeing Company",
  "YWCA Washington",
  "Allied Universal Security Services",
  "Harborstone Credit Union",
  "Allegis Group",
  "NCESD",
  "Gebber's Farm",
  "Alaska Airlines",
  "The Pokemon Company International",
  "SIA Partners US",
  "Inc.",
  "HCL Technologies",
  "AIM Consulting",
  "Microsoft Corporation",
  "JPMorgan Chase Corporation",
  "Accenture",
  "Sure Start",
  "Chenega Agile Real-Time Solution",
  "Cyborg Mobile",
  "AllCoveredPainting.com",
  "Pierce County",
  "Pacific Northwest National Laboratory",
  "Green River College",
  "RMS Computer Corporation",
  "Amazon Development Center",
  "Wenatchee Valley College",
  "Chelan County PUD",
  "CyrusOne",
  "Gray & Osborne Engineering Consulting",
  "ATS Automation",
  "Audere",
  "Highline College",
  "Crane Aerospace & Electronics",
  "FDM Group",
  "Inc.",
  "Year Up Professional Resources",
  "Per Scholas",
  "Wenatchee School District",
  "ACI",
  "Mindtrust",
  "TTBH",
  "Apex Systems",
  "Columbia Distributing",
  "Right Systems Inc.",
  "BAE Systems",
  "Winter Park Resorts",
  "The Metropolitan Water District of Southern California",
  "Keller Rohrbrack L.L.P.",
  "Dataprise",
  "McCall Communications Consulting",
  "Oak Ridge National Laboratory",
  "Outlier",
  "Blue Origin",
  "Ezsvs usa inc",
  "Amy's Kitchen",
  "Nisqually Indian Tribe",
  "Carnegie Mellon University",
  "Helpful Computing LLC",
];
