import '@/app/ui/global.css';
import Footer from '@/app/ui/Footer';
import SignupHeader from '@/app/ui/SignupHeader';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`antialiased min-h-screen flex flex-col`}>
        <SignupHeader/>
        {children}
        <footer className='mt-auto'><Footer/></footer>
        
      </body>
    </html>
  )
}
