import '@/app/ui/global.css';
import CFAFooter from '@/app/ui/CFAFooter';
import CFASignupHeader from '@/app/ui/CFASignupHeader';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`antialiased min-h-screen flex flex-col`}>
        <CFASignupHeader></CFASignupHeader>
        {children}
        <footer className='mt-auto'><CFAFooter></CFAFooter></footer>
        
      </body>
    </html>
  )
}
