BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[RAGRecordManager] (
    [id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [RAGRecordManager_id_df] DEFAULT newid(),
    [updatedAt] DATETIME NOT NULL CONSTRAINT [RAGRecordManager_updatedAt_df] DEFAULT CURRENT_TIMESTAMP,
    [createdAt] DATETIME NOT NULL CONSTRAINT [RAGRecordManager_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [fileId] TEXT NOT NULL,
    [hash] TEXT NOT NULL,
    CONSTRAINT [RAGRecordManager_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
