BEGIN TRANSACTION;

INSERT INTO [dbo].[socc_2018] (socc_code, title, description)
SELECT v.socc_code, v.title, v.description
FROM (VALUES ('999999', 'No Match', NULL),
             ('191011', 'Animal Scientists', NULL),
             ('191012', 'Food Scientists and Technologists', NULL),
             ('191013', 'Soil and Plant Scientists', NULL),
             ('194012', 'Agricultural Technicians', NULL),
             ('251041', 'Agricultural Sciences Teachers, Postsecondary', NULL),
             ('119013', 'Farmers, Ranchers, and Other Agricultural Managers', NULL),
             ('451011', 'First-Line Supervisors of Farming, Fishing, and Forestry Workers', NULL),
             ('193011', 'Economists', NULL),
             ('251063', 'Economics Teachers, Postsecondary', NULL),
             ('259021', 'Farm and Home Management Educators', NULL),
             ('131021', 'Buyers and Purchasing Agents, Farm Products', NULL),
             ('414012', 'Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products',
              NULL),
             ('151232', 'Computer User Support Specialists', NULL),
             ('431011', 'First-Line Supervisors of Office and Administrative Support Workers', NULL),
             ('493041', 'Farm Equipment Mechanics and Service Technicians', NULL),
             ('452091', 'Agricultural Equipment Operators', NULL),
             ('493011', 'Aircraft Mechanics and Service Technicians', NULL),
             ('493042', 'Mobile Heavy Equipment Mechanics, Except Engines', NULL),
             ('251194', 'Career/Technical Education Teachers, Postsecondary', NULL),
             ('452021', 'Animal Breeders', NULL),
             ('191031', 'Conservation Scientists', NULL),
             ('251043', 'Forestry and Conservation Science Teachers, Postsecondary', NULL),
             ('452093', 'Farmworkers, Farm, Ranch, and Aquacultural Animals', NULL),
             ('194013', 'Food Science Technicians', NULL),
             ('452011', 'Agricultural Inspectors', NULL),
             ('392021', 'Animal Caretakers', NULL),
             ('392011', 'Animal Trainers', NULL),
             ('371012', 'First-Line Supervisors of Landscaping, Lawn Service, and Groundskeeping Workers', NULL),
             ('373011', 'Landscaping and Groundskeeping Workers', NULL),
             ('373012', 'Pesticide Handlers, Sprayers, and Applicators, Vegetation', NULL),
             ('454011', 'Forest and Conservation Workers', NULL),
             ('411011', 'First-Line Supervisors of Retail Sales Workers', NULL),
             ('273023', 'News Analysts, Reporters, and Journalists', NULL),
             ('274011', 'Audio and Video Technicians', NULL),
             ('513092', 'Food Batchmakers', NULL),
             ('519012',
              'Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Tenders',
              NULL),
             ('191022', 'Microbiologists', NULL),
             ('251071', 'Health Specialties Teachers, Postsecondary', NULL),
             ('291131', 'Veterinarians', NULL),
             ('119111', 'Medical and Health Services Managers', NULL),
             ('436013', 'Medical Secretaries and Administrative Assistants', NULL),
             ('111021', 'General and Operations Managers', NULL),
             ('113012', 'Administrative Services Managers', NULL),
             ('434171', 'Receptionists and Information Clerks', NULL),
             ('292056', 'Veterinary Technologists and Technicians', NULL),
             ('319096', 'Veterinary Assistants and Laboratory Animal Caretakers', NULL),
             ('191032', 'Foresters', NULL),
             ('194071', 'Forest and Conservation Technicians', NULL),
             ('131041', 'Compliance Officers', NULL),
             ('192041', 'Environmental Scientists and Specialists, Including Health', NULL),
             ('251053', 'Environmental Science Teachers, Postsecondary', NULL),
             ('194042', 'Environmental Science and Protection Technicians, Including Health', NULL),
             ('119072', 'Entertainment and Recreation Managers, Except Gambling', NULL),
             ('251111', 'Criminal Justice and Law Enforcement Teachers, Postsecondary', NULL),
             ('331012', 'First-Line Supervisors of Police and Detectives', NULL),
             ('331021', 'First-Line Supervisors of Firefighting and Prevention Workers', NULL),
             ('332011', 'Firefighters', NULL),
             ('332022', 'Forest Fire Inspectors and Prevention Specialists', NULL),
             ('333021', 'Detectives and Criminal Investigators', NULL),
             ('333031', 'Fish and Game Wardens', NULL),
             ('333051', N'Police and Sheriff’s Patrol Officers', NULL),
             ('339092', 'Lifeguards, Ski Patrol, and Other Recreational Protective Service Workers', NULL),
             ('193099', 'Social Scientists and Related Workers, All Other', NULL),
             ('453031', 'Fishing and Hunting Workers', NULL),
             ('191023', 'Zoologists and Wildlife Biologists', NULL),
             ('119041', 'Architectural and Engineering Managers', NULL),
             ('171011', 'Architects, Except Landscape and Naval', NULL),
             ('251031', 'Architecture Teachers, Postsecondary', NULL),
             ('193051', 'Urban and Regional Planners', NULL),
             ('251069', 'Social Sciences Teachers, Postsecondary, All Other', NULL),
             ('171012', 'Landscape Architects', NULL),
             ('271025', 'Interior Designers', NULL),
             ('193093', 'Historians', NULL),
             ('173011', 'Architectural and Civil Drafters', NULL),
             ('119141', 'Property, Real Estate, and Community Association Managers', NULL),
             ('132023', 'Appraisers and Assessors of Real Estate', NULL),
             ('419021', 'Real Estate Brokers', NULL),
             ('419022', 'Real Estate Sales Agents', NULL),
             ('251062', 'Area, Ethnic, and Cultural Studies Teachers, Postsecondary', NULL),
             ('273091', 'Interpreters and Translators', NULL),
             ('112032', 'Public Relations Managers', NULL),
             ('112033', 'Fundraising Managers', NULL),
             ('131131', 'Fundraisers', NULL),
             ('251122', 'Communications Teachers, Postsecondary', NULL),
             ('273011', 'Broadcast Announcers and Radio Disc Jockeys', NULL),
             ('273031', 'Public Relations Specialists', NULL),
             ('273041', 'Editors', NULL),
             ('273043', 'Writers and Authors', NULL),
             ('273099', 'Media and Communication Workers, All Other', NULL),
             ('439081', 'Proofreaders and Copy Markers', NULL),
             ('274021', 'Photographers', NULL),
             ('274032', 'Film and Video Editors', NULL),
             ('272012', 'Producers and Directors', NULL),
             ('119199', 'Managers, All Other', NULL),
             ('151255', 'Web and Digital Interface Designers', NULL),
             ('112011', 'Advertising and Promotions Managers', NULL),
             ('113121', 'Human Resources Managers', NULL),
             ('113131', 'Training and Development Managers', NULL),
             ('131151', 'Training and Development Specialists', NULL),
             ('211091', 'Health Education Specialists', NULL),
             ('211094', 'Community Health Workers', NULL),
             ('131011', 'Agents and Business Managers of Artists, Performers, and Athletes', NULL),
             ('272099', 'Entertainers and Performers, Sports and Related Workers, All Other', NULL),
             ('273042', 'Technical Writers', NULL),
             ('274012', 'Broadcast Technicians', NULL),
             ('274014', 'Sound Engineering Technicians', NULL),
             ('274015', 'Lighting Technicians', NULL),
             ('274031', 'Camera Operators, Television, Video, and Film', NULL),
             ('272091', 'Disc Jockeys, Except Radio', NULL),
             ('273092', 'Court Reporters and Simultaneous Captioners', NULL),
             ('515111', 'Prepress Technicians and Workers', NULL),
             ('515112', 'Printing Press Operators', NULL),
             ('439031', 'Desktop Publishers', NULL),
             ('271014', 'Special Effects Artists and Animators', NULL),
             ('439021', 'Data Entry Keyers', NULL),
             ('519194', 'Etchers and Engravers', NULL),
             ('113021', 'Computer and Information Systems Managers', NULL),
             ('151211', 'Computer Systems Analysts', NULL),
             ('151221', 'Computer and Information Research Scientists', NULL),
             ('151241', 'Computer Network Architects', NULL),
             ('151242', 'Database Administrators', NULL),
             ('151243', 'Database Architects', NULL),
             ('151244', 'Network and Computer Systems Administrators', NULL),
             ('151253', 'Software Quality Assurance Analysts and Testers', NULL),
             ('151299', 'Computer Occupations, All Other', NULL),
             ('251021', 'Computer Science Teachers, Postsecondary', NULL),
             ('151252', 'Software Developers', NULL),
             ('152051', 'Data Scientists', NULL),
             ('151212', 'Information Security Analysts', NULL),
             ('151231', 'Computer Network Support Specialists', NULL),
             ('151251', 'Computer Programmers', NULL),
             ('151254', 'Web Developers', NULL),
             ('439022', 'Word Processors and Typists', NULL),
             ('271024', 'Graphic Designers', NULL),
             ('131082', 'Project Management Specialists', NULL),
             ('119171', 'Funeral Home Managers', NULL),
             ('394011', 'Embalmers', NULL),
             ('394031', 'Morticians, Undertakers, and Funeral Arrangers', NULL),
             ('394012', 'Crematory Operators', NULL),
             ('395012', 'Hairdressers, Hairstylists, and Cosmetologists', NULL),
             ('395091', 'Makeup Artists, Theatrical and Performance', NULL),
             ('395092', 'Manicurists and Pedicurists', NULL),
             ('395093', 'Shampooers', NULL),
             ('395094', 'Skincare Specialists', NULL),
             ('395011', 'Barbers', NULL),
             ('119179', 'Personal Service Managers, All Other', NULL),
             ('391022', 'First-Line Supervisors of Personal Service Workers', NULL),
             ('351011', 'Chefs and Head Cooks', NULL),
             ('351012', 'First-Line Supervisors of Food Preparation and Serving Workers', NULL),
             ('352012', 'Cooks, Institution and Cafeteria', NULL),
             ('352014', 'Cooks, Restaurant', NULL),
             ('352019', 'Cooks, All Other', NULL),
             ('513011', 'Bakers', NULL),
             ('353011', 'Bartenders', NULL),
             ('352013', 'Cooks, Private Household', NULL),
             ('119051', 'Food Service Managers', NULL),
             ('513021', 'Butchers and Meat Cutters', NULL),
             ('513023', 'Slaughterers and Meat Packers', NULL),
             ('251199', 'Postsecondary Teachers, All Other', NULL),
             ('131022', 'Wholesale and Retail Buyers, Except Farm Products', NULL),
             ('339031', 'Gambling Surveillance Officers and Gambling Investigators', NULL),
             ('391013', 'First-Line Supervisors of Gambling Services Workers', NULL),
             ('433041', 'Gambling Cage Workers', NULL),
             ('393011', 'Gambling Dealers', NULL),
             ('396012', 'Concierges', NULL),
             ('251081', 'Education Teachers, Postsecondary', NULL),
             ('259042',
              'Teaching Assistants, Preschool, Elementary, Middle, and Secondary School, Except Special Education',
              NULL),
             ('259043', 'Teaching Assistants, Special Education', NULL),
             ('252011', 'Preschool Teachers, Except Special Education', NULL),
             ('252012', 'Kindergarten Teachers, Except Special Education', NULL),
             ('252021', 'Elementary School Teachers, Except Special Education', NULL),
             ('252022', 'Middle School Teachers, Except Special and Career/Technical Education', NULL),
             ('252031', 'Secondary School Teachers, Except Special and Career/Technical Education', NULL),
             ('253011',
              'Adult Basic Education, Adult Secondary Education, and English as a Second Language Instructors', NULL),
             ('253099', 'Teachers and Instructors, All Other', NULL),
             ('259031', 'Instructional Coordinators', NULL),
             ('119031', 'Education and Childcare Administrators, Preschool and Daycare', NULL),
             ('119032', 'Education Administrators, Kindergarten through Secondary', NULL),
             ('119033', 'Education Administrators, Postsecondary', NULL),
             ('119039', 'Education Administrators, All Other', NULL),
             ('254022', 'Librarians and Media Collections Specialists', NULL),
             ('131111', 'Management Analysts', NULL),
             ('152041', 'Statisticians', NULL),
             ('259099', 'Educational Instruction and Library Workers, All Other', NULL),
             ('193022', 'Survey Researchers', NULL),
             ('252051', 'Special Education Teachers, Preschool', NULL),
             ('252055', 'Special Education Teachers, Kindergarten', NULL),
             ('252056', 'Special Education Teachers, Elementary School', NULL),
             ('252057', 'Special Education Teachers, Middle School', NULL),
             ('252058', 'Special Education Teachers, Secondary School', NULL),
             ('252059', 'Special Education Teachers, All Other', NULL),
             ('211012', 'Educational, Guidance, and Career Counselors and Advisors', NULL),
             ('399041', 'Residential Advisors', NULL),
             ('253021', 'Self-Enrichment Teachers', NULL),
             ('252023', 'Career/Technical Education Teachers, Middle School', NULL),
             ('252032', 'Career/Technical Education Teachers, Secondary School', NULL),
             ('251121', 'Art, Drama, and Music Teachers, Postsecondary', NULL),
             ('251011', 'Business Teachers, Postsecondary', NULL),
             ('251123', 'English Language and Literature Teachers, Postsecondary', NULL),
             ('251124', 'Foreign Language and Literature Teachers, Postsecondary', NULL),
             ('251192', 'Family and Consumer Sciences Teachers, Postsecondary', NULL),
             ('251022', 'Mathematical Science Teachers, Postsecondary', NULL),
             ('251193', 'Recreation and Fitness Studies Teachers, Postsecondary', NULL),
             ('272022', 'Coaches and Scouts', NULL),
             ('399031', 'Exercise Trainers and Group Fitness Instructors', NULL),
             ('251042', 'Biological Science Teachers, Postsecondary', NULL),
             ('251051', 'Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary', NULL),
             ('251052', 'Chemistry Teachers, Postsecondary', NULL),
             ('251054', 'Physics Teachers, Postsecondary', NULL),
             ('251125', 'History Teachers, Postsecondary', NULL),
             ('251064', 'Geography Teachers, Postsecondary', NULL),
             ('251066', 'Psychology Teachers, Postsecondary', NULL),
             ('259049', 'Teaching Assistants, All Other', NULL),
             ('259044', 'Teaching Assistants, Postsecondary', NULL),
             ('172199', 'Engineers, All Other', NULL),
             ('251032', 'Engineering Teachers, Postsecondary', NULL),
             ('172011', 'Aerospace Engineers', NULL),
             ('173021', 'Aerospace Engineering and Operations Technologists and Technicians', NULL),
             ('492091', 'Avionics Technicians', NULL),
             ('172021', 'Agricultural Engineers', NULL),
             ('172031', 'Bioengineers and Biomedical Engineers', NULL),
             ('172041', 'Chemical Engineers', NULL),
             ('172131', 'Materials Engineers', NULL),
             ('172051', 'Civil Engineers', NULL),
             ('172081', 'Environmental Engineers', NULL),
             ('172151', 'Mining and Geological Engineers, Including Mining Safety Engineers', NULL),
             ('172171', 'Petroleum Engineers', NULL),
             ('172061', 'Computer Hardware Engineers', NULL),
             ('172071', 'Electrical Engineers', NULL),
             ('172072', 'Electronics Engineers, Except Computer', NULL),
             ('172141', 'Mechanical Engineers', NULL),
             ('119121', 'Natural Sciences Managers', NULL),
             ('192012', 'Physicists', NULL),
             ('172111', 'Health and Safety Engineers, Except Mining Safety Engineers and Inspectors', NULL),
             ('131051', 'Cost Estimators', NULL),
             ('172121', 'Marine Engineers and Naval Architects', NULL),
             ('172161', 'Nuclear Engineers', NULL),
             ('172112', 'Industrial Engineers', NULL),
             ('113051', 'Industrial Production Managers', NULL),
             ('152031', 'Operations Research Analysts', NULL),
             ('171021', 'Cartographers and Photogrammetrists', NULL),
             ('171022', 'Surveyors', NULL),
             ('173022', 'Civil Engineering Technologists and Technicians', NULL),
             ('173023', 'Electrical and Electronic Engineering Technologists and Technicians', NULL),
             ('173024', 'Electro-Mechanical and Mechatronics Technologists and Technicians', NULL),
             ('173026', 'Industrial Engineering Technologists and Technicians', NULL),
             ('173029', 'Engineering Technologists and Technicians, Except Drafters, All Other', NULL),
             ('536041', 'Traffic Technicians', NULL),
             ('173012', 'Electrical and Electronics Drafters', NULL),
             ('173028', 'Calibration Technologists and Technicians', NULL),
             ('492095', 'Electrical and Electronics Repairers, Powerhouse, Substation, and Relay', NULL),
             ('499062', 'Medical Equipment Repairers', NULL),
             ('499069', 'Precision Instrument and Equipment Repairers, All Other', NULL),
             ('499021', 'Heating, Air Conditioning, and Refrigeration Mechanics and Installers', NULL),
             ('173025', 'Environmental Engineering Technologists and Technicians', NULL),
             ('518031', 'Water and Wastewater Treatment Plant and System Operators', NULL),
             ('474041', 'Hazardous Materials Removal Workers', NULL),
             ('514121', 'Welders, Cutters, Solderers, and Brazers', NULL),
             ('519141', 'Semiconductor Processing Technicians', NULL),
             ('195011', 'Occupational Health and Safety Specialists', NULL),
             ('519061', 'Inspectors, Testers, Sorters, Samplers, and Weighers', NULL),
             ('195012', 'Occupational Health and Safety Technicians', NULL),
             ('173013', 'Mechanical Drafters', NULL),
             ('173027', 'Mechanical Engineering Technologists and Technicians', NULL),
             ('493023', 'Automotive Service Technicians and Mechanics', NULL),
             ('493051', 'Motorboat Mechanics and Service Technicians', NULL),
             ('194043', 'Geological Technicians, Except Hydrologic Technicians', NULL),
             ('475013', 'Service Unit Operators, Oil and Gas', NULL),
             ('518092', 'Gas Plant Operators', NULL),
             ('119021', 'Construction Managers', NULL),
             ('173019', 'Drafters, All Other', NULL),
             ('173031', 'Surveying and Mapping Technicians', NULL),
             ('194051', 'Nuclear Technicians', NULL),
             ('113013', 'Facilities Managers', NULL),
             ('271021', 'Commercial and Industrial Designers', NULL),
             ('518013', 'Power Plant Operators', NULL),
             ('472231', 'Solar Photovoltaic Installers', NULL),
             ('499081', 'Wind Turbine Service Technicians', NULL),
             ('112021', 'Marketing Managers', NULL),
             ('112022', 'Sales Managers', NULL),
             ('131161', 'Market Research Analysts and Marketing Specialists', NULL),
             ('132052', 'Personal Financial Advisors', NULL),
             ('291031', 'Dietitians and Nutritionists', NULL),
             ('292051', 'Dietetic Technicians', NULL),
             ('131121', 'Meeting, Convention, and Event Planners', NULL),
             ('193039', 'Psychologists, All Other', NULL),
             ('399011', 'Childcare Workers', NULL),
             ('211093', 'Social and Human Service Assistants', NULL),
             ('211099', 'Community and Social Service Specialists, All Other', NULL),
             ('271022', 'Fashion Designers', NULL),
             ('516092', 'Fabric and Apparel Patternmakers', NULL),
             ('192032', 'Materials Scientists', NULL),
             ('232011', 'Paralegals and Legal Assistants', NULL),
             ('232099', 'Legal Support Workers, All Other', NULL),
             ('231011', 'Lawyers', NULL),
             ('231012', 'Judicial Law Clerks', NULL),
             ('231021', 'Administrative Law Judges, Adjudicators, and Hearing Officers', NULL),
             ('231022', 'Arbitrators, Mediators, and Conciliators', NULL),
             ('231023', 'Judges, Magistrate Judges, and Magistrates', NULL),
             ('251112', 'Law Teachers, Postsecondary', NULL),
             ('436012', 'Legal Secretaries and Administrative Assistants', NULL),
             ('232093', 'Title Examiners, Abstractors, and Searchers', NULL),
             ('251082', 'Library Science Teachers, Postsecondary', NULL),
             ('254011', 'Archivists', NULL),
             ('254031', 'Library Technicians', NULL),
             ('191029', 'Biological Scientists, All Other', NULL),
             ('191099', 'Life Scientists, All Other', NULL),
             ('194021', 'Biological Technicians', NULL),
             ('194092', 'Forensic Science Technicians', NULL),
             ('191042', 'Medical Scientists, Except Epidemiologists', NULL),
             ('191021', 'Biochemists and Biophysicists', NULL),
             ('191041', 'Epidemiologists', NULL),
             ('292011', 'Medical and Clinical Laboratory Technologists', NULL),
             ('299092', 'Genetic Counselors', NULL),
             ('291128', 'Exercise Physiologists', NULL),
             ('152099', 'Mathematical Science Occupations, All Other', NULL),
             ('152021', 'Mathematicians', NULL),
             ('152011', 'Actuaries', NULL),
             ('132051', 'Financial and Investment Analysts', NULL),
             ('132054', 'Financial Risk Specialists', NULL),
             ('132099', 'Financial Specialists, All Other', NULL),
             ('551019', 'Military Officer Special and Tactical Operations Leaders, All Other', NULL),
             ('551017', 'Special Forces Officers', NULL),
             ('553018', 'Special Forces', NULL),
             ('553019', 'Military Enlisted Tactical Operations and Air/Weapons Specialists and Crew Members, All Other',
              NULL),
             ('551016', 'Infantry Officers', NULL),
             ('551014', 'Artillery and Missile Officers', NULL),
             ('553014', 'Artillery and Missile Crew Members', NULL),
             ('551015', 'Command and Control Center Officers', NULL),
             ('553015', 'Command and Control Center Specialists', NULL),
             ('553012', 'Aircraft Launch and Recovery Specialists', NULL),
             ('251113', 'Social Work Teachers, Postsecondary', NULL),
             ('254012', 'Curators', NULL),
             ('254013', 'Museum Technicians and Conservators', NULL),
             ('113031', 'Financial Managers', NULL),
             ('132011', 'Accountants and Auditors', NULL),
             ('119151', 'Social and Community Service Managers', NULL),
             ('194061', 'Social Science Research Assistants', NULL),
             ('192099', 'Physical Scientists, All Other', NULL),
             ('193094', 'Political Scientists', NULL),
             ('193091', 'Anthropologists and Archeologists', NULL),
             ('251061', 'Anthropology and Archeology Teachers, Postsecondary', NULL),
             ('212021', 'Directors, Religious Activities and Education', NULL),
             ('212099', 'Religious Workers, All Other', NULL),
             ('131075', 'Labor Relations Specialists', NULL),
             ('192042', 'Geoscientists, Except Hydrologists and Geographers', NULL),
             ('192021', 'Atmospheric and Space Scientists', NULL),
             ('193092', 'Geographers', NULL),
             ('192043', 'Hydrologists', NULL),
             ('251065', 'Political Science Teachers, Postsecondary', NULL),
             ('251126', 'Philosophy and Religion Teachers, Postsecondary', NULL),
             ('211019', 'Counselors, All Other', NULL),
             ('211022', 'Healthcare Social Workers', NULL),
             ('272021', 'Athletes and Sports Competitors', NULL),
             ('299091', 'Athletic Trainers', NULL),
             ('391014', 'First-Line Supervisors of Entertainment and Recreation Workers, Except Gambling Services',
              NULL),
             ('399032', 'Recreation Workers', NULL),
             ('272041', 'Music Directors and Composers', NULL),
             ('212011', 'Clergy', NULL),
             ('192011', 'Astronomers', NULL),
             ('194099', 'Life, Physical, and Social Science Technicians, All Other', NULL),
             ('192031', 'Chemists', NULL),
             ('194031', 'Chemical Technicians', NULL),
             ('194044', 'Hydrologic Technicians', NULL),
             ('518011', 'Nuclear Power Reactor Operators', NULL),
             ('518091', 'Chemical Plant and System Operators', NULL),
             ('519011', 'Chemical Equipment Operators and Tenders', NULL),
             ('193032', 'Industrial-Organizational Psychologists', NULL),
             ('193033', 'Clinical and Counseling Psychologists', NULL),
             ('211021', 'Child, Family, and School Social Workers', NULL),
             ('211014', 'Mental Health Counselors', NULL),
             ('131071', 'Human Resources Specialists', NULL),
             ('193034', 'School Psychologists', NULL),
             ('331011', 'First-Line Supervisors of Correctional Officers', NULL),
             ('333012', 'Correctional Officers and Jailers', NULL),
             ('333011', 'Bailiffs', NULL),
             ('339021', 'Private Detectives and Investigators', NULL),
             ('331091', 'First-Line Supervisors of Security Workers', NULL),
             ('333052', 'Transit and Railroad Police', NULL),
             ('339032', 'Security Guards', NULL),
             ('331099', 'First-Line Supervisors of Protective Service Workers, All Other', NULL),
             ('119161', 'Emergency Management Directors', NULL),
             ('132061', 'Financial Examiners', NULL),
             ('332021', 'Fire Inspectors and Investigators', NULL),
             ('434061', 'Eligibility Interviewers, Government Programs', NULL),
             ('111011', 'Chief Executives', NULL),
             ('111031', 'Legislators', NULL),
             ('113071', 'Transportation, Storage, and Distribution Managers', NULL),
             ('119131', 'Postmasters and Mail Superintendents', NULL),
             ('211013', 'Marriage and Family Therapists', NULL),
             ('211023', 'Mental Health and Substance Abuse Social Workers', NULL),
             ('211029', 'Social Workers, All Other', NULL),
             ('211092', 'Probation Officers and Correctional Treatment Specialists', NULL),
             ('193041', 'Sociologists', NULL),
             ('251067', 'Sociology Teachers, Postsecondary', NULL),
             ('397011', 'Tour Guides and Escorts', NULL),
             ('471011', 'First-Line Supervisors of Construction Trades and Extraction Workers', NULL),
             ('472021', 'Brickmasons and Blockmasons', NULL),
             ('472022', 'Stonemasons', NULL),
             ('472044', 'Tile and Stone Setters', NULL),
             ('472031', 'Carpenters', NULL),
             ('491011', 'First-Line Supervisors of Mechanics, Installers, and Repairers', NULL),
             ('499051', 'Electrical Power-Line Installers and Repairers', NULL),
             ('472111', 'Electricians', NULL),
             ('492098', 'Security and Fire Alarm Systems Installers', NULL),
             ('499097', 'Signal and Track Switch Repairers', NULL),
             ('371011', 'First-Line Supervisors of Housekeeping and Janitorial Workers', NULL),
             ('499071', 'Maintenance and Repair Workers, General', NULL),
             ('472051', 'Cement Masons and Concrete Finishers', NULL),
             ('474011', 'Construction and Building Inspectors', NULL),
             ('472081', 'Drywall and Ceiling Tile Installers', NULL),
             ('472121', 'Glaziers', NULL),
             ('472141', 'Painters, Construction and Maintenance', NULL),
             ('472142', 'Paperhangers', NULL),
             ('472181', 'Roofers', NULL),
             ('472221', 'Structural Iron and Steel Workers', NULL),
             ('499095', 'Manufactured Building and Mobile Home Installers', NULL),
             ('472041', 'Carpet Installers', NULL),
             ('472042', 'Floor Layers, Except Carpet, Wood, and Hard Tiles', NULL),
             ('472043', 'Floor Sanders and Finishers', NULL),
             ('472053', 'Terrazzo Workers and Finishers', NULL),
             ('472131', 'Insulation Workers, Floor, Ceiling, and Wall', NULL),
             ('472132', 'Insulation Workers, Mechanical', NULL),
             ('472152', 'Plumbers, Pipefitters, and Steamfitters', NULL),
             ('474071', 'Septic Tank Servicers and Sewer Pipe Cleaners', NULL),
             ('475011', 'Derrick Operators, Oil and Gas', NULL),
             ('475012', 'Rotary Drill Operators, Oil and Gas', NULL),
             ('475023', 'Earth Drillers, Except Oil and Gas', NULL),
             ('475032', 'Explosives Workers, Ordnance Handling Experts, and Blasters', NULL),
             ('499099', 'Installation, Maintenance, and Repair Workers, All Other', NULL),
             ('492092', 'Electric Motor, Power Tool, and Related Repairers', NULL),
             ('492011', 'Computer, Automated Teller, and Office Machine Repairers', NULL),
             ('432099', 'Communications Equipment Operators, All Other', NULL),
             ('492021', 'Radio, Cellular, and Tower Equipment Installers and Repairers', NULL),
             ('492022', 'Telecommunications Equipment Installers and Repairers, Except Line Installers', NULL),
             ('492097', 'Audiovisual Equipment Installers and Repairers', NULL),
             ('499052', 'Telecommunications Line Installers and Repairers', NULL),
             ('492094', 'Electrical and Electronics Repairers, Commercial and Industrial Equipment', NULL),
             ('499031', 'Home Appliance Repairers', NULL),
             ('493043', 'Rail Car Repairers', NULL),
             ('499012', 'Control and Valve Installers and Repairers, Except Mechanical Door', NULL),
             ('474021', 'Elevator and Escalator Installers and Repairers', NULL),
             ('499041', 'Industrial Machinery Mechanics', NULL),
             ('499043', 'Maintenance Workers, Machinery', NULL),
             ('499044', 'Millwrights', NULL),
             ('499045', 'Refractory Materials Repairers, Except Brickmasons', NULL),
             ('499094', 'Locksmiths and Safe Repairers', NULL),
             ('499063', 'Musical Instrument Repairers and Tuners', NULL),
             ('499064', 'Watch and Clock Repairers', NULL),
             ('512061', 'Timing Device Assemblers and Adjusters', NULL),
             ('519071', 'Jewelers and Precious Stone and Metal Workers', NULL),
             ('499061', 'Camera and Photographic Equipment Repairers', NULL),
             ('131032', 'Insurance Appraisers, Auto Damage', NULL),
             ('493021', 'Automotive Body and Related Repairers', NULL),
             ('493022', 'Automotive Glass Installers and Repairers', NULL),
             ('519124', 'Coating, Painting, and Spraying Machine Setters, Operators, and Tenders', NULL),
             ('492093', 'Electrical and Electronics Installers and Repairers, Transportation Equipment', NULL),
             ('492096', 'Electronic Equipment Installers and Repairers, Motor Vehicles', NULL),
             ('493031', 'Bus and Truck Mechanics and Diesel Engine Specialists', NULL),
             ('493053', 'Outdoor Power Equipment and Other Small Engine Mechanics', NULL),
             ('512011', 'Aircraft Structure, Surfaces, Rigging, and Systems Assemblers', NULL),
             ('493091', 'Bicycle Repairers', NULL),
             ('493052', 'Motorcycle Mechanics', NULL),
             ('512031', 'Engine and Other Machine Assemblers', NULL),
             ('493092', 'Recreational Vehicle Service Technicians', NULL),
             ('516093', 'Upholsterers', NULL),
             ('516041', 'Shoe and Leather Workers and Repairers', NULL),
             ('516042', 'Shoe Machine Operators and Tenders', NULL),
             ('514021', 'Extruding and Drawing Machine Setters, Operators, and Tenders, Metal and Plastic', NULL),
             ('514022', 'Forging Machine Setters, Operators, and Tenders, Metal and Plastic', NULL),
             ('514023', 'Rolling Machine Setters, Operators, and Tenders, Metal and Plastic', NULL),
             ('514031', 'Cutting, Punching, and Press Machine Setters, Operators, and Tenders, Metal and Plastic',
              NULL),
             ('514032', 'Drilling and Boring Machine Tool Setters, Operators, and Tenders, Metal and Plastic', NULL),
             ('514033',
              'Grinding, Lapping, Polishing, and Buffing Machine Tool Setters, Operators, and Tenders, Metal and Plastic',
              NULL),
             ('514034', 'Lathe and Turning Machine Tool Setters, Operators, and Tenders, Metal and Plastic', NULL),
             ('514035', 'Milling and Planing Machine Setters, Operators, and Tenders, Metal and Plastic', NULL),
             ('514041', 'Machinists', NULL),
             ('514081', 'Multiple Machine Tool Setters, Operators, and Tenders, Metal and Plastic', NULL),
             ('514191', 'Heat Treating Equipment Setters, Operators, and Tenders, Metal and Plastic', NULL),
             ('514192', 'Layout Workers, Metal and Plastic', NULL),
             ('514199', 'Metal Workers and Plastic Workers, All Other', NULL),
             ('512041', 'Structural Metal Fabricators and Fitters', NULL),
             ('514194', 'Tool Grinders, Filers, and Sharpeners', NULL),
             ('519161', 'Computer Numerically Controlled Tool Operators', NULL),
             ('472211', 'Sheet Metal Workers', NULL),
             ('514061', 'Model Makers, Metal and Plastic', NULL),
             ('514062', 'Patternmakers, Metal and Plastic', NULL),
             ('514111', 'Tool and Die Makers', NULL),
             ('514122', 'Welding, Soldering, and Brazing Machine Setters, Operators, and Tenders', NULL),
             ('514071', 'Foundry Mold and Coremakers', NULL),
             ('519162', 'Computer Numerically Controlled Tool Programmers', NULL),
             ('517042', 'Woodworking Machine Setters, Operators, and Tenders, Except Sawing', NULL),
             ('517099', 'Woodworkers, All Other', NULL),
             ('517021', 'Furniture Finishers', NULL),
             ('517011', 'Cabinetmakers and Bench Carpenters', NULL),
             ('517031', 'Model Makers, Wood', NULL),
             ('517032', 'Patternmakers, Wood', NULL),
             ('517041', 'Sawing Machine Setters, Operators, and Tenders, Wood', NULL),
             ('472011', 'Boilermakers', NULL),
             ('532011', 'Airline Pilots, Copilots, and Flight Engineers', NULL),
             ('532012', 'Commercial Pilots', NULL),
             ('532021', 'Air Traffic Controllers', NULL),
             ('532022', 'Airfield Operations Specialists', NULL),
             ('531044', 'First-Line Supervisors of Passenger Attendants', NULL),
             ('532031', 'Flight Attendants', NULL),
             ('454022', 'Logging Equipment Operators', NULL),
             ('472071', 'Paving, Surfacing, and Tamping Equipment Operators', NULL),
             ('472072', 'Pile Driver Operators', NULL),
             ('472073', 'Operating Engineers and Other Construction Equipment Operators', NULL),
             ('474051', 'Highway Maintenance Workers', NULL),
             ('474061', 'Rail-Track Laying and Maintenance Equipment Operators', NULL),
             ('475022', 'Excavating and Loading Machine and Dragline Operators, Surface Mining', NULL),
             ('475041', 'Continuous Mining Machine Operators', NULL),
             ('475049', 'Underground Mining Machine Operators, All Other', NULL),
             ('475099', 'Extraction Workers, All Other', NULL),
             ('537021', 'Crane and Tower Operators', NULL),
             ('537031', 'Dredge Operators', NULL),
             ('537041', 'Hoist and Winch Operators', NULL),
             ('537199', 'Material Moving Workers, All Other', NULL),
             ('533032', 'Heavy and Tractor-Trailer Truck Drivers', NULL),
             ('533033', 'Light Truck Drivers', NULL),
             ('533051', 'Bus Drivers, School', NULL),
             ('533052', 'Bus Drivers, Transit and Intercity', NULL),
             ('533053', 'Shuttle Drivers and Chauffeurs', NULL),
             ('531043', 'First-Line Supervisors of Material-Moving Machine and Vehicle Operators', NULL),
             ('531049', 'First-Line Supervisors of Transportation Workers, All Other', NULL),
             ('534011', 'Locomotive Engineers', NULL),
             ('534013', 'Rail Yard Engineers, Dinkey Operators, and Hostlers', NULL),
             ('534022', 'Railroad Brake, Signal, and Switch Operators and Locomotive Firers', NULL),
             ('534031', 'Railroad Conductors and Yardmasters', NULL),
             ('534041', 'Subway and Streetcar Operators', NULL),
             ('534099', 'Rail Transportation Workers, All Other', NULL),
             ('537051', 'Industrial Truck and Tractor Operators', NULL),
             ('535021', 'Captains, Mates, and Pilots of Water Vessels', NULL),
             ('499092', 'Commercial Divers', NULL),
             ('535022', 'Motorboat Operators', NULL),
             ('535031', 'Ship Engineers', NULL),
             ('271012', 'Craft Artists', NULL),
             ('271013', 'Fine Artists, Including Painters, Sculptors, and Illustrators', NULL),
             ('271019', 'Artists and Related Workers, All Other', NULL),
             ('271011', 'Art Directors', NULL),
             ('272031', 'Dancers', NULL),
             ('272032', 'Choreographers', NULL),
             ('271027', 'Set and Exhibit Designers', NULL),
             ('271029', 'Designers, All Other', NULL),
             ('272011', 'Actors', NULL),
             ('272042', 'Musicians and Singers', NULL),
             ('393092', 'Costume Attendants', NULL),
             ('132022', 'Appraisers of Personal and Business Property', NULL),
             ('291011', 'Chiropractors', NULL),
             ('291127', 'Speech-Language Pathologists', NULL),
             ('291181', 'Audiologists', NULL),
             ('291021', 'Dentists, General', NULL),
             ('291029', 'Dentists, All Other Specialists', NULL),
             ('291022', 'Oral and Maxillofacial Surgeons', NULL),
             ('291023', 'Orthodontists', NULL),
             ('291024', 'Prosthodontists', NULL),
             ('319091', 'Dental Assistants', NULL),
             ('291292', 'Dental Hygienists', NULL),
             ('519081', 'Dental Laboratory Technicians', NULL),
             ('319099', 'Healthcare Support Workers, All Other', NULL),
             ('292072', 'Medical Records Specialists', NULL),
             ('299021', 'Health Information Technologists and Medical Registrars', NULL),
             ('319094', 'Medical Transcriptionists', NULL),
             ('299099', 'Healthcare Practitioners and Technical Workers, All Other', NULL),
             ('319092', 'Medical Assistants', NULL),
             ('131031', 'Claims Adjusters, Examiners, and Investigators', NULL),
             ('292012', 'Medical and Clinical Laboratory Technicians', NULL),
             ('312011', 'Occupational Therapy Assistants', NULL),
             ('292052', 'Pharmacy Technicians', NULL),
             ('312021', 'Physical Therapist Assistants', NULL),
             ('533011', 'Ambulance Drivers and Attendants, Except Emergency Medical Technicians', NULL),
             ('292055', 'Surgical Technologists', NULL),
             ('292099', 'Health Technologists and Technicians, All Other', NULL),
             ('292031', 'Cardiovascular Technologists and Technicians', NULL),
             ('292042', 'Emergency Medical Technicians', NULL),
             ('292043', 'Paramedics', NULL),
             ('292033', 'Nuclear Medicine Technologists', NULL),
             ('291124', 'Radiation Therapists', NULL),
             ('292034', 'Radiologic Technologists and Technicians', NULL),
             ('292036', 'Medical Dosimetrists', NULL),
             ('291126', 'Respiratory Therapists', NULL),
             ('299093', 'Surgical Assistants', NULL),
             ('292032', 'Diagnostic Medical Sonographers', NULL),
             ('291071', 'Physician Assistants', NULL),
             ('292092', 'Hearing Aid Specialists', NULL),
             ('292035', 'Magnetic Resonance Imaging Technologists', NULL),
             ('519083', 'Ophthalmic Laboratory Technicians', NULL),
             ('319097', 'Phlebotomists', NULL),
             ('319093', 'Medical Equipment Preparers', NULL),
             ('291211', 'Anesthesiologists', NULL),
             ('291212', 'Cardiologists', NULL),
             ('291213', 'Dermatologists', NULL),
             ('291214', 'Emergency Medicine Physicians', NULL),
             ('291215', 'Family Medicine Physicians', NULL),
             ('291216', 'General Internal Medicine Physicians', NULL),
             ('291217', 'Neurologists', NULL),
             ('291218', 'Obstetricians and Gynecologists', NULL),
             ('291221', 'Pediatricians, General', NULL),
             ('291222', 'Physicians, Pathologists', NULL),
             ('291223', 'Psychiatrists', NULL),
             ('291224', 'Radiologists', NULL),
             ('291229', 'Physicians, All Other', NULL),
             ('291241', 'Ophthalmologists, Except Pediatric', NULL),
             ('291242', 'Orthopedic Surgeons, Except Pediatric', NULL),
             ('291243', 'Pediatric Surgeons', NULL),
             ('291249', 'Surgeons, All Other', NULL),
             ('291081', 'Podiatrists', NULL),
             ('211011', 'Substance Abuse and Behavioral Disorder Counselors', NULL),
             ('292053', 'Psychiatric Technicians', NULL),
             ('311133', 'Psychiatric Aides', NULL),
             ('291041', 'Optometrists', NULL),
             ('292081', 'Opticians, Dispensing', NULL),
             ('292057', 'Ophthalmic Medical Technicians', NULL),
             ('291051', 'Pharmacists', NULL),
             ('291129', 'Therapists, All Other', NULL),
             ('291122', 'Occupational Therapists', NULL),
             ('292091', 'Orthotists and Prosthetists', NULL),
             ('519082', 'Medical Appliance Technicians', NULL),
             ('291123', 'Physical Therapists', NULL),
             ('291125', 'Recreational Therapists', NULL),
             ('211015', 'Rehabilitation Counselors', NULL),
             ('311131', 'Nursing Assistants', NULL),
             ('311121', 'Home Health Aides', NULL),
             ('311122', 'Personal Care Aides', NULL),
             ('312012', 'Occupational Therapy Aides', NULL),
             ('312022', 'Physical Therapist Aides', NULL),
             ('251072', 'Nursing Instructors and Teachers, Postsecondary', NULL),
             ('291299', 'Healthcare Diagnosing or Treating Practitioners, All Other', NULL),
             ('291291', 'Acupuncturists', NULL),
             ('319011', 'Massage Therapists', NULL),
             ('291141', 'Registered Nurses', NULL),
             ('291171', 'Nurse Practitioners', NULL),
             ('291151', 'Nurse Anesthetists', NULL),
             ('291161', 'Nurse Midwives', NULL),
             ('292061', 'Licensed Practical and Licensed Vocational Nurses', NULL),
             ('113111', 'Compensation and Benefits Managers', NULL),
             ('131081', 'Logisticians', NULL),
             ('131141', 'Compensation, Benefits, and Job Analysis Specialists', NULL),
             ('131199', 'Business Operations Specialists, All Other', NULL),
             ('113061', 'Purchasing Managers', NULL),
             ('131023', 'Purchasing Agents, Except Wholesale, Retail, and Farm Products', NULL),
             ('511011', 'First-Line Supervisors of Production and Operating Workers', NULL),
             ('132053', 'Insurance Underwriters', NULL),
             ('132031', 'Budget Analysts', NULL),
             ('132041', 'Credit Analysts', NULL),
             ('132081', 'Tax Examiners and Collectors, and Revenue Agents', NULL),
             ('132082', 'Tax Preparers', NULL),
             ('433031', 'Bookkeeping, Accounting, and Auditing Clerks', NULL),
             ('433051', 'Payroll and Timekeeping Clerks', NULL),
             ('434011', 'Brokerage Clerks', NULL),
             ('439111', 'Statistical Assistants', NULL),
             ('434161', 'Human Resources Assistants, Except Payroll and Timekeeping', NULL),
             ('436011', 'Executive Secretaries and Executive Administrative Assistants', NULL),
             ('436014', 'Secretaries and Administrative Assistants, Except Legal, Medical, and Executive', NULL),
             ('434051', 'Customer Service Representatives', NULL),
             ('434151', 'Order Clerks', NULL),
             ('433061', 'Procurement Clerks', NULL),
             ('434021', 'Correspondence Clerks', NULL),
             ('434071', 'File Clerks', NULL),
             ('435011', 'Cargo and Freight Agents', NULL),
             ('439041', 'Insurance Claims and Policy Processing Clerks', NULL),
             ('439061', 'Office Clerks, General', NULL),
             ('435061', 'Production, Planning, and Expediting Clerks', NULL),
             ('435032', 'Dispatchers, Except Police, Fire, and Ambulance', NULL),
             ('132072', 'Loan Officers', NULL),
             ('132071', 'Credit Counselors', NULL),
             ('433011', 'Bill and Account Collectors', NULL),
             ('433071', 'Tellers', NULL),
             ('434041', 'Credit Authorizers, Checkers, and Clerks', NULL),
             ('434131', 'Loan Interviewers and Clerks', NULL),
             ('434141', 'New Accounts Clerks', NULL),
             ('413031', 'Securities, Commodities, and Financial Services Sales Agents', NULL),
             ('119081', 'Lodging Managers', NULL),
             ('397012', 'Travel Guides', NULL),
             ('119071', 'Gambling Managers', NULL),
             ('413021', 'Insurance Sales Agents', NULL),
             ('413091',
              'Sales Representatives of Services, Except Advertising, Insurance, Financial Services, and Travel', NULL),
             ('419011', 'Demonstrators and Product Promoters', NULL),
             ('419099', 'Sales and Related Workers, All Other', NULL),
             ('411012', 'First-Line Supervisors of Non-Retail Sales Workers', NULL),
             ('412022', 'Parts Salespersons', NULL),
             ('413011', 'Advertising Sales Agents', NULL),
             ('413041', 'Travel Agents', NULL),
             ('414011', 'Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products', NULL),
             ('271026', 'Merchandise Displayers and Window Trimmers', NULL),
             ('419012', 'Models', NULL),
             ('131074', 'Farm Labor Contractors', NULL),
             ('253031', 'Substitute Teachers, Short-Term', NULL),
             ('253041', 'Tutors', NULL),
             ('271023', 'Floral Designers', NULL),
             ('272023', 'Umpires, Referees, and Other Sports Officials', NULL),
             ('274099', 'Media and Communication Equipment Workers, All Other', NULL),
             ('311132', 'Orderlies', NULL),
             ('319095', 'Pharmacy Aides', NULL),
             ('333041', 'Parking Enforcement Workers', NULL),
             ('339011', 'Animal Control Workers', NULL),
             ('339091', 'Crossing Guards and Flaggers', NULL),
             ('339093', 'Transportation Security Screeners', NULL),
             ('339094', 'School Bus Monitors', NULL),
             ('339099', 'Protective Service Workers, All Other', NULL),
             ('352011', 'Cooks, Fast Food', NULL),
             ('352015', 'Cooks, Short Order', NULL),
             ('352021', 'Food Preparation Workers', NULL),
             ('353023', 'Fast Food and Counter Workers', NULL),
             ('353031', 'Waiters and Waitresses', NULL),
             ('353041', 'Food Servers, Nonrestaurant', NULL),
             ('359011', 'Dining Room and Cafeteria Attendants and Bartender Helpers', NULL),
             ('359021', 'Dishwashers', NULL),
             ('359031', 'Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop', NULL),
             ('359099', 'Food Preparation and Serving Related Workers, All Other', NULL),
             ('372011', 'Janitors and Cleaners, Except Maids and Housekeeping Cleaners', NULL),
             ('372012', 'Maids and Housekeeping Cleaners', NULL),
             ('372019', 'Building Cleaning Workers, All Other', NULL),
             ('372021', 'Pest Control Workers', NULL),
             ('373013', 'Tree Trimmers and Pruners', NULL),
             ('373019', 'Grounds Maintenance Workers, All Other', NULL),
             ('393012', 'Gambling and Sports Book Writers and Runners', NULL),
             ('393019', 'Gambling Service Workers, All Other', NULL),
             ('393021', 'Motion Picture Projectionists', NULL),
             ('393031', 'Ushers, Lobby Attendants, and Ticket Takers', NULL),
             ('393091', 'Amusement and Recreation Attendants', NULL),
             ('393093', 'Locker Room, Coatroom, and Dressing Room Attendants', NULL),
             ('393099', 'Entertainment Attendants and Related Workers, All Other', NULL),
             ('394021', 'Funeral Attendants', NULL),
             ('396011', 'Baggage Porters and Bellhops', NULL),
             ('399099', 'Personal Care and Service Workers, All Other', NULL),
             ('412011', 'Cashiers', NULL),
             ('412012', 'Gambling Change Persons and Booth Cashiers', NULL),
             ('412021', 'Counter and Rental Clerks', NULL),
             ('412031', 'Retail Salespersons', NULL),
             ('419031', 'Sales Engineers', NULL),
             ('419041', 'Telemarketers', NULL),
             ('419091', 'Door-to-Door Sales Workers, News and Street Vendors, and Related Workers', NULL),
             ('432011', 'Switchboard Operators, Including Answering Service', NULL),
             ('432021', 'Telephone Operators', NULL),
             ('433021', 'Billing and Posting Clerks', NULL),
             ('433099', 'Financial Clerks, All Other', NULL),
             ('434031', 'Court, Municipal, and License Clerks', NULL),
             ('434081', 'Hotel, Motel, and Resort Desk Clerks', NULL),
             ('434111', 'Interviewers, Except Eligibility and Loan', NULL),
             ('434121', 'Library Assistants, Clerical', NULL),
             ('434181', 'Reservation and Transportation Ticket Agents and Travel Clerks', NULL),
             ('434199', 'Information and Record Clerks, All Other', NULL),
             ('435021', 'Couriers and Messengers', NULL),
             ('435031', 'Public Safety Telecommunicators', NULL),
             ('435041', 'Meter Readers, Utilities', NULL),
             ('435051', 'Postal Service Clerks', NULL),
             ('435052', 'Postal Service Mail Carriers', NULL),
             ('435053', 'Postal Service Mail Sorters, Processors, and Processing Machine Operators', NULL),
             ('435071', 'Shipping, Receiving, and Inventory Clerks', NULL),
             ('435111', 'Weighers, Measurers, Checkers, and Samplers, Recordkeeping', NULL),
             ('439051', 'Mail Clerks and Mail Machine Operators, Except Postal Service', NULL),
             ('439071', 'Office Machine Operators, Except Computer', NULL),
             ('439199', 'Office and Administrative Support Workers, All Other', NULL),
             ('452041', 'Graders and Sorters, Agricultural Products', NULL),
             ('452092', 'Farmworkers and Laborers, Crop, Nursery, and Greenhouse', NULL),
             ('452099', 'Agricultural Workers, All Other', NULL),
             ('454021', 'Fallers', NULL),
             ('454023', 'Log Graders and Scalers', NULL),
             ('454029', 'Logging Workers, All Other', NULL),
             ('472061', 'Construction Laborers', NULL),
             ('472082', 'Tapers', NULL),
             ('472151', 'Pipelayers', NULL),
             ('472161', 'Plasterers and Stucco Masons', NULL),
             ('472171', 'Reinforcing Iron and Rebar Workers', NULL),
             ('473011', 'Helpers--Brickmasons, Blockmasons, Stonemasons, and Tile and Marble Setters', NULL),
             ('473012', 'Helpers--Carpenters', NULL),
             ('473013', 'Helpers--Electricians', NULL),
             ('473014', 'Helpers--Painters, Paperhangers, Plasterers, and Stucco Masons', NULL),
             ('473015', 'Helpers--Pipelayers, Plumbers, Pipefitters, and Steamfitters', NULL),
             ('473016', 'Helpers--Roofers', NULL),
             ('473019', 'Helpers, Construction Trades, All Other', NULL),
             ('474031', 'Fence Erectors', NULL),
             ('474091', 'Segmental Pavers', NULL),
             ('474099', 'Construction and Related Workers, All Other', NULL),
             ('475043', 'Roof Bolters, Mining', NULL),
             ('475044', 'Loading and Moving Machine Operators, Underground Mining', NULL),
             ('475051', 'Rock Splitters, Quarry', NULL),
             ('475071', 'Roustabouts, Oil and Gas', NULL),
             ('475081', 'Helpers--Extraction Workers', NULL),
             ('493093', 'Tire Repairers and Changers', NULL),
             ('499011', 'Mechanical Door Repairers', NULL),
             ('499091', 'Coin, Vending, and Amusement Machine Servicers and Repairers', NULL),
             ('499096', 'Riggers', NULL),
             ('499098', 'Helpers--Installation, Maintenance, and Repair Workers', NULL),
             ('512021', 'Coil Winders, Tapers, and Finishers', NULL),
             ('512022', 'Electrical and Electronic Equipment Assemblers', NULL),
             ('512023', 'Electromechanical Equipment Assemblers', NULL),
             ('512051', 'Fiberglass Laminators and Fabricators', NULL),
             ('512092', 'Team Assemblers', NULL),
             ('512099', 'Assemblers and Fabricators, All Other', NULL),
             ('513022', 'Meat, Poultry, and Fish Cutters and Trimmers', NULL),
             ('513091', 'Food and Tobacco Roasting, Baking, and Drying Machine Operators and Tenders', NULL),
             ('513093', 'Food Cooking Machine Operators and Tenders', NULL),
             ('513099', 'Food Processing Workers, All Other', NULL),
             ('514051', 'Metal-Refining Furnace Operators and Tenders', NULL),
             ('514052', 'Pourers and Casters, Metal', NULL),
             ('514072', 'Molding, Coremaking, and Casting Machine Setters, Operators, and Tenders, Metal and Plastic',
              NULL),
             ('514193', 'Plating Machine Setters, Operators, and Tenders, Metal and Plastic', NULL),
             ('515113', 'Print Binding and Finishing Workers', NULL),
             ('516011', 'Laundry and Dry-Cleaning Workers', NULL),
             ('516021', 'Pressers, Textile, Garment, and Related Materials', NULL),
             ('516031', 'Sewing Machine Operators', NULL),
             ('516051', 'Sewers, Hand', NULL),
             ('516052', 'Tailors, Dressmakers, and Custom Sewers', NULL),
             ('516061', 'Textile Bleaching and Dyeing Machine Operators and Tenders', NULL),
             ('516062', 'Textile Cutting Machine Setters, Operators, and Tenders', NULL),
             ('516063', 'Textile Knitting and Weaving Machine Setters, Operators, and Tenders', NULL),
             ('516064', 'Textile Winding, Twisting, and Drawing Out Machine Setters, Operators, and Tenders', NULL),
             ('516091', 'Extruding and Forming Machine Setters, Operators, and Tenders, Synthetic and Glass Fibers',
              NULL),
             ('516099', 'Textile, Apparel, and Furnishings Workers, All Other', NULL),
             ('518012', 'Power Distributors and Dispatchers', NULL),
             ('518021', 'Stationary Engineers and Boiler Operators', NULL),
             ('518093', 'Petroleum Pump System Operators, Refinery Operators, and Gaugers', NULL),
             ('518099', 'Plant and System Operators, All Other', NULL),
             ('519021', 'Crushing, Grinding, and Polishing Machine Setters, Operators, and Tenders', NULL),
             ('519022', 'Grinding and Polishing Workers, Hand', NULL),
             ('519023', 'Mixing and Blending Machine Setters, Operators, and Tenders', NULL),
             ('519031', 'Cutters and Trimmers, Hand', NULL),
             ('519032', 'Cutting and Slicing Machine Setters, Operators, and Tenders', NULL),
             ('519041', 'Extruding, Forming, Pressing, and Compacting Machine Setters, Operators, and Tenders', NULL),
             ('519051', 'Furnace, Kiln, Oven, Drier, and Kettle Operators and Tenders', NULL),
             ('519111', 'Packaging and Filling Machine Operators and Tenders', NULL),
             ('519123', 'Painting, Coating, and Decorating Workers', NULL),
             ('519151', 'Photographic Process Workers and Processing Machine Operators', NULL),
             ('519191', 'Adhesive Bonding Machine Operators and Tenders', NULL),
             ('519192', 'Cleaning, Washing, and Metal Pickling Equipment Operators and Tenders', NULL),
             ('519193', 'Cooling and Freezing Equipment Operators and Tenders', NULL),
             ('519195', 'Molders, Shapers, and Casters, Except Metal and Plastic', NULL),
             ('519196', 'Paper Goods Machine Setters, Operators, and Tenders', NULL),
             ('519197', 'Tire Builders', NULL),
             ('519198', 'Helpers--Production Workers', NULL),
             ('519199', 'Production Workers, All Other', NULL),
             ('531041', 'Aircraft Cargo Handling Supervisors', NULL),
             ('531042', 'First-Line Supervisors of Helpers, Laborers, and Material Movers, Hand', NULL),
             ('533031', 'Driver/Sales Workers', NULL),
             ('533054', 'Taxi Drivers', NULL),
             ('533099', 'Motor Vehicle Operators, All Other', NULL),
             ('535011', 'Sailors and Marine Oilers', NULL),
             ('536011', 'Bridge and Lock Tenders', NULL),
             ('536021', 'Parking Attendants', NULL),
             ('536031', 'Automotive and Watercraft Service Attendants', NULL),
             ('536032', 'Aircraft Service Attendants', NULL),
             ('536051', 'Transportation Inspectors', NULL),
             ('536061', 'Passenger Attendants', NULL),
             ('536099', 'Transportation Workers, All Other', NULL),
             ('537011', 'Conveyor Operators and Tenders', NULL),
             ('537061', 'Cleaners of Vehicles and Equipment', NULL),
             ('537062', 'Laborers and Freight, Stock, and Material Movers, Hand', NULL),
             ('537063', 'Machine Feeders and Offbearers', NULL),
             ('537064', 'Packers and Packagers, Hand', NULL),
             ('537065', 'Stockers and Order Fillers', NULL),
             ('537071', 'Gas Compressor and Gas Pumping Station Operators', NULL),
             ('537072', 'Pump Operators, Except Wellhead Pumpers', NULL),
             ('537073', 'Wellhead Pumpers', NULL),
             ('537081', 'Refuse and Recyclable Material Collectors', NULL),
             ('537121', 'Tank Car, Truck, and Ship Loaders', NULL),
             ('551011', 'Air Crew Officers', NULL),
             ('551012', 'Aircraft Launch and Recovery Officers', NULL),
             ('551013', 'Armored Assault Vehicle Officers', NULL),
             ('552011', 'First-Line Supervisors of Air Crew Members', NULL),
             ('552012', 'First-Line Supervisors of Weapons Specialists/Crew Members', NULL),
             ('552013', 'First-Line Supervisors of All Other Tactical Operations Specialists', NULL),
             ('553011', 'Air Crew Members', NULL),
             ('553013', 'Armored Assault Vehicle Crew Members', NULL),
             ('553016', 'Infantry', NULL)) AS v(socc_code, title, description)
WHERE NOT EXISTS (SELECT 1
                  FROM [dbo].[socc_2018] t
                  WHERE t.socc_code = v.socc_code);

COMMIT;
