BEGIN TRANSACTION;

-- 1) Define and populate the in‐memory mapping table
DECLARE @SkillMap TABLE (
                            skill_name       VARCHAR(255) NOT NULL,
                            subcategory_name VARCHAR(255) NULL
                        );

INSERT INTO @SkillMap (skill_name, subcategory_name)
VALUES
    ('Ability to explain technical concepts clearly to non-technical users', 'Technical Support Services'),
    ('Ajax'                  , 'Web Design and Development'),
    ('Agile methodologies'                  , 'Agile Software Development'),
    ('Scrum'                                , 'Agile Software Development'),
    ('User story'                           , 'Agile Software Development'),
    ('Consuming APIs'                       , 'Application Programming Interfaces (API)'),
    ('Hyperparameter optimization'          , 'Artificial Intelligence and Machine Learning (AI/ML)'),
    ('Natural language processing'          , 'Artificial Intelligence and Machine Learning (AI/ML)'),
    ('Predictive analytics'                 , 'Artificial Intelligence and Machine Learning (AI/ML)'),
    ('Predictive modeling'                  , 'Artificial Intelligence and Machine Learning (AI/ML)'),
    ('Disaster recovery'                    , 'Backup Software'),
    ('Network disaster recovery'            , 'Backup Software'),
    ('Business analysis'                    , 'Business Intelligence'),
    ('Business intelligence'                , 'Business Intelligence'),
    ('Competitive analysis'                 , 'Business Intelligence'),
    ('Define and analyze business problems and reframe it as an analytic problem', 'Business Intelligence'),
    ('Define key metrics for success'       , 'Business Intelligence'),
    ('Determine information, analysis, and data required to support decision making and answer the business problem', 'Business Intelligence'),
    ('Develop a proposed set of drivers and relationships to outputs, assumptions and constraints', 'Business Intelligence'),
    ('Gap analysis'                         , 'Business Intelligence'),
    ('Identify enhancements based on performance data', 'Business Intelligence'),
    ('Key performance indicators'           , 'Business Intelligence'),
    ('Reporting'                            , 'Business Intelligence'),
    ('Business development'                 , 'Business Operations'),
    ('Business operations'                  , 'Business Operations'),
    ('Business process'                     , 'Business Operations'),
    ('Business requirements'                , 'Business Operations'),
    ('Business strategies'                  , 'Business Operations'),
    ('Product strategy'                     , 'Business Operations'),
    ('Requirement definition/design'        , 'Business Operations'),
    ('C++'                                  , 'C and C++'),
    ('AWS'                                  , 'Cloud Computing'),
    ('Azure Databricks'                     , 'Cloud Computing'),
    ('Cloud compute'                        , 'Cloud Computing'),
    ('Cloud service (e.g., Microsoft Azure, AWS)', 'Cloud Computing'),
    ('Deploying in the cloud'               , 'Cloud Computing'),
    ('SaaS'                                 , 'Cloud Solutions'),
    ('Snowflake cloud'                      , 'Cloud Solutions'),
    ('SharePoint'                           , 'Collaborative Software'),
    ('Social media'                         , 'Collaborative Software'),
    ('Computer hardware (desktops, laptops, peripherals)', 'Computer Hardware'),
    ('CLI configuration'                    , 'Configuration Management'),
    ('Configuration management (Ansible, Terraform, Puppet, Chef)', 'Configuration Management'),
    ('Docker Products'                      , NULL),
    ('Delivery content via CMS and delivery platforms', 'Content Management Systems'),
    ('Apply cybersecurity and privacy principles to organizational requirements', 'Cybersecurity'),
    ('Assess security controls based on cybersecurity principles and tenets', 'Cybersecurity'),
    ('Assess security systems designs'      , 'Cybersecurity'),
    ('Auditing'                             , 'Cybersecurity'),
    ('Auditing and reporting'               , 'Cybersecurity'),
    ('Compliant development'                , 'Cybersecurity'),
    ('Continuous monitoring'                , 'Cybersecurity'),
    ('Cyber threat intelligence'            , 'Cybersecurity'),
    ('Cybersecurity'                        , 'Cybersecurity'),
    ('Determine how a security system should work and how changes will affect outcomes', 'Cybersecurity'),
    ('Develop and apply security system access controls', 'Cybersecurity'),
    ('Evaluate the adequacy of security designs', 'Cybersecurity'),
    ('Laws and regulations on data protection and privacy and security', 'Cybersecurity'),
    ('Manual malware analysis'              , 'Cybersecurity'),
    ('Open web application security project', 'Cybersecurity'),
    ('Recognize vulnerabilities in security systems', 'Cybersecurity'),
    ('Regulatory compliance'                , 'Cybersecurity'),
    ('Risk analysis'                        , 'Cybersecurity'),
    ('Risk management'                      , 'Cybersecurity'),
    ('Risk mitigation'                      , 'Cybersecurity'),
    ('Secure code development'              , 'Cybersecurity'),
    ('Security awareness'                   , 'Cybersecurity'),
    ('Security controls'                    , 'Cybersecurity'),
    ('Security policies'                    , 'Cybersecurity'),
    ('Benchmarking/ data/ metrics'          , 'Data Management'),
    ('Big data'                             , 'Data Management'),
    ('Data and knowledge driven problem definition and solving', 'Data Management'),
    ('Data cleansing'                       , 'Data Management'),
    ('Data engineering'                     , 'Data Management'),
    ('Data modeling'                        , 'Data Management'),
    ('Data preprocessing'                   , 'Data Management'),
    ('Identify sources, uses, and characteristics of a data set', 'Data Management'),
    ('Manage and maintain data'             , 'Data Management'),
    ('Organizing, creating, consuming, and rending data', 'Data Management'),
    ('Create and use statistical models'    , 'Data Science'),
    ('Data analysis'                        , 'Data Science'),
    ('Data analytics'                       , 'Data Science'),
    ('Data mining'                          , 'Data Science'),
    ('Data science'                         , 'Data Science'),
    ('Explore, organize, clean, transform and visualize data using Microsoft Excel, SQL, and Tableau', 'Data Science'),
    ('Interpret results and draw meaningful conclusions', 'Data Science'),
    ('MATLAB'                               , 'Data Science'),
    ('Data warehousing'                     , 'Data Storage'),
    ('Dashboard'                            , 'Data Visualization'),
    ('Data dashboards'                      , 'Data Visualization'),
    ('Data visualization'                   , 'Data Visualization'),
    ('Microsoft Excel'                      , 'Data Visualization'),
    ('Monitor performance of the solution against predefined KPIs using dashboards', 'Data Visualization'),
    ('Hive'                                 , 'Databases'),
    ('Microsoft SQL server'                 , 'Databases'),
    ('Distributed systems'                  , 'Distributed Computing'),
    ('Hadoop'                               , 'Distributed Computing'),
    ('Geometric dimensioning'               , NULL),
    ('Enterprise software'                  , 'Enterprise Application Management'),
    ('SAP applications'                     , 'Enterprise Application Management'),
    ('XML'                                  , 'Extensible Languages and XML'),
    ('Apache spark'                         , 'Extraction, Transformation, and Loading (ETL)'),
    ('Extract, transform, load'             , 'Extraction, Transformation, and Loading (ETL)'),
    ('PySpark'                              , 'Extraction, Transformation, and Loading (ETL)'),
    ('Local area networks (LANs)'           , 'General Networking'),
    ('Networking fundamentals (LAN, Wi-Fi)' , 'General Networking'),
    ('Access controls'                      , 'Identity and Access Management'),
    ('Access management (Active directory, LDAP, IAM)', 'Identity and Access Management'),
    ('Identity & access management'         , 'Identity and Access Management'),
    ('Eclipse'                              , 'Integrated Development Environments (IDEs)'),
    ('Integration & interoperability'       , 'IT Automation'),
    ('DevSecOps'                            , 'IT Automation'),
    ('Change management'                    , 'IT Management'),
    ('Governance'                           , 'IT Management'),
    ('IT strategy'                          , 'IT Management'),
    ('Java'                                 , 'Java'),
    ('Angular'                              , 'JavaScript and jQuery'),
    ('AngularJS'                            , 'JavaScript and jQuery'),
    ('Security information and event management', 'Malware Protection'),
    ('Microsoft exchange'                   , 'Microsoft Development Tools'),
    ('Integration software'                 , 'Middleware'),
    ('Software integration'                 , 'Middleware'),
    ('Network design'                       , 'Network Protocols'),
    ('Network quality of service'           , 'Network Protocols'),
    ('Sd-wan'                               , 'Network Protocols'),
    ('WAN protocols'                        , 'Network Protocols'),
    ('Wide area networks edge connectivity' , 'Network Protocols'),
    ('Virtual private networks'             , 'Network Security'),
    ('Operating systems (Linux, Windows 10; Unix)', 'Operating Systems'),
    ('Operating systems (Windows 10, macOS, potentially Linux)', 'Operating Systems'),
    ('OS architecture internals'            , 'Operating Systems'),
    ('Windows server'                       , 'Operating Systems'),
    ('Hibernate'                            , 'Other Programming Languages'),
    ('NumPy'                                , 'Other Programming Languages'),
    ('Pandas'                               , 'Other Programming Languages'),
    ('Programming ability/languages'        , 'Other Programming Languages'),
    ('Scala'                                , 'Other Programming Languages'),
    ('SQL'                                  , 'Query Languages'),
    ('Finite element analysis'              , NULL),
    ('Mechanical engineering'               , NULL),
    ('Scientific research'                  , NULL),
    ('Scripting (Python, PowerShell, Bash)' , 'Scripting'),
    ('Powershell'                           , 'Scripting Languages'),
    ('Shell scripting'                      , 'Scripting Languages'),
    ('Querying media'                       , 'Search Engines'),
    ('Tomcat'                               , 'Servers'),
    ('Ability to think creatively and adapt to different situations', 'Soft Skill'),
    ('Ability to work under pressure and meet deadlines', 'Soft Skill'),
    ('Active listening'                     , 'Soft Skill'),
    ('Adaptability'                         , 'Soft Skill'),
    ('Analytical skills'                    , 'Soft Skill'),
    ('Analytical skills to identify root causes of issues', 'Soft Skill'),
    ('Analytical thinking'                  , 'Soft Skill'),
    ('Collaboration'                        , 'Soft Skill'),
    ('Communicate findings to stakeholders' , 'Soft Skill'),
    ('Communication'                        , 'Soft Skill'),
    ('Complex problem-solving'              , 'Soft Skill'),
    ('Continuous process improvement'       , 'Soft Skill'),
    ('Conversationalist'                    , 'Soft Skill'),
    ('Coordinating'                         , 'Soft Skill'),
    ('Creativity'                           , 'Soft Skill'),
    ('Critical problem solving'             , 'Soft Skill'),
    ('Critical thinking'                    , 'Soft Skill'),
    ('Cross functional team leadership'     , 'Soft Skill'),
    ('Customer problem solving'             , 'Soft Skill'),
    ('Customer relationship management'     , 'Soft Skill'),
    ('Customer service'                     , 'Soft Skill'),
    ('Decision making'                      , 'Soft Skill'),
    ('Demonstrating responsibility'         , 'Soft Skill'),
    ('Describe scenarios'                   , 'Soft Skill'),
    ('Detail oriented'                      , 'Soft Skill'),
    ('Detail-oriented'                      , 'Soft Skill'),
    ('Digital marketing'                    , 'Soft Skill'),
    ('Documentation maintenance'            , 'Soft Skill'),
    ('Effective communication'              , 'Soft Skill'),
    ('Emotional intelligence'               , 'Soft Skill'),
    ('Empathy'                              , 'Soft Skill'),
    ('Excellent verbal and written communication', 'Soft Skill'),
    ('Finance'                              , 'Soft Skill'),
    ('Innovation'                           , 'Soft Skill'),
    ('Interpersonal collaboration'          , 'Soft Skill'),
    ('Interpersonal communications'         , 'Soft Skill'),
    ('Investigation'                        , 'Soft Skill'),
    ('Knowledge base maintenance'           , 'Soft Skill'),
    ('Leadership'                           , 'Soft Skill'),
    ('Leadership demonstration'             , 'Soft Skill'),
    ('Make iterations'                      , 'Soft Skill'),
    ('Management'                           , 'Soft Skill'),
    ('Management consulting'                , 'Soft Skill'),
    ('Marketing'                            , 'Soft Skill'),
    ('Multitasking'                         , 'Soft Skill'),
    ('New product development'              , 'Soft Skill'),
    ('Operations'                           , 'Soft Skill'),
    ('Organizational skills'                , 'Soft Skill'),
    ('Patience'                             , 'Soft Skill'),
    ('Patience and ability to handle difficult situations', 'Soft Skill'),
    ('Planning'                             , 'Soft Skill'),
    ('Presentation'                         , 'Soft Skill'),
    ('Presentation skills'                  , 'Soft Skill'),
    ('Presentations'                        , 'Soft Skill'),
    ('Prioritization'                       , 'Soft Skill'),
    ('Prioritization and multitasking'      , 'Soft Skill'),
    ('Problem solving'                      , 'Soft Skill'),
    ('Problem-solving'                      , 'Soft Skill'),
    ('Process improvement'                  , 'Soft Skill'),
    ('Project coordination'                 , 'Soft Skill'),
    ('Project management'                   , 'Soft Skill'),
    ('Project planning and developing'      , 'Soft Skill'),
    ('Project risk management'              , 'Soft Skill'),
    ('Project team management'              , 'Soft Skill'),
    ('Research information'                 , 'Soft Skill'),
    ('Resource and workflow management'     , 'Soft Skill'),
    ('Sales'                                , 'Soft Skill'),
    ('Self-motivation'                      , 'Soft Skill'),
    ('Stakeholder management'               , 'Soft Skill'),
    ('Standard operating procedure'         , 'Soft Skill'),
    ('Strategic planning'                   , 'Soft Skill'),
    ('Strong communication'                 , 'Soft Skill'),
    ('Strong customer focus and empathy'    , 'Soft Skill'),
    ('Systems thinking'                     , 'Soft Skill'),
    ('Task coordination'                    , 'Soft Skill'),
    ('Teamwork and collaboration'           , 'Soft Skill'),
    ('Technical proficiency'                , 'Soft Skill'),
    ('Time management'                      , 'Soft Skill'),
    ('Training and development'             , 'Soft Skill'),
    ('Triage'                               , 'Soft Skill'),
    ('Vendor management'                    , 'Soft Skill'),
    ('Verbal and written communication'     , 'Soft Skill'),
    ('Verbal and written communications'    , 'Soft Skill'),
    ('Workflow management'                  , 'Soft Skill'),
    ('Writing'                              , 'Soft Skill'),
    ('Write code in a currently supported programming language', 'Software Development'),
    ('Back-end development for websites'    , 'Software Development'),
    ('Building a webserver in Node.js'      , 'Software Development'),
    ('Designing and creating basic functions and algorithms', 'Software Development'),
    ('Engineering software'                 , 'Software Development'),
    ('Full stack software frameworks'       , 'Software Development'),
    ('HW-SW full stack debug'               , 'Software Development'),
    ('Object oriented design'               , 'Software Development'),
    ('Product development life cycle'       , 'Software Development'),
    ('Write code in a currently supported programming language', 'Software Development'),
    ('XML'                                  , 'Extensible Languages and XML'),
    ('Design the integration of hardware and software solutions', 'Cybersecurity'),
    ('Architecture definition',                                               'System Design and Implementation'),
    ('Architecture modeling',                                                  'System Design and Implementation'),
    ('Automation testing',                                                     'Test Automation'),
    ('CAD',                                                                    'Software Development Tools'),
    ('CATIA',                                                                  'Software Development Tools'),
    ('Communication of architectural intent',                                   'System Design and Implementation'),
    ('Conduct usability tests and incorporate results into design process',     'Web Design and Development'),
    ('Create personas',                                                         'Web Design and Development'),
    ('Create prototype',                                                        'Web Design and Development'),
    ('CSS',                                                                    'Web Design and Development'),
    ('Descriptive statistics',                                                 'Statistical Modeling'),
    ('Design and evaluate experiments',                                         'Statistical Modeling'),
    ('Design patterns',                                                        'System Design and Implementation'),
    ('Develop user flows',                                                      'Web Design and Development'),
    ('Development design',                                                      'Software Development Tools'),
    ('Docker Products',                                                         'Virtualization and Virtual Machines'),
    ('End-user training',                                                       'Technical Support and Services'),
    ('Figma (design software)',                                                 'Web Design and Development'),
    ('Finite element analysis',                                                 NULL),
    ('Front-end development for website including HTML5, CSS, JavaScript Git GitHub and version control', 'Web Design and Development'),
    ('Geometric dimensioning',                                                  NULL),
    ('Git',                                                                    'Version Control'),
    ('Help desk software (ServiceNow, Zendesk, etc.)',                          'Technical Support and Services'),
    ('High level software design',                                             'System Design and Implementation'),
    ('High-level software design',                                              'System Design and Implementation'),
    ('HTML',                                                                   'Web Design and Development'),
    ('Implementing responsive images and typography',                           'Web Design and Development'),
    ('Implementing solutions and workarounds',                                  'Technical Support and Services'),
    ('Managing Linux and Windows servers',                                      'Systems Administration'),
    ('Mathematics',                                                            'Statistical Modeling'),
    ('Mechanical engineering',                                                  NULL),
    ('Microsoft office',                                                        'Basic Technical Knowledge'),
    ('Microsoft Office suite (Word, Excel, Outlook, PowerPoint)',               'Basic Technical Knowledge'),
    ('Microsoft Power BI',                                                      'Data Visualization'),
    ('Performance optimization and total cost of ownership',                    'System Design and Implementation'),
    ('Personnel procedures',                                                    'Systems Administration'),
    ('Power BI',                                                               'Data Visualization'),
    ('Product design',                                                         'System Design and Implementation'),
    ('Project management software',                                            'Software Development Tools'),
    ('Prototyping',                                                            'Web Design and Development'),
    ('PTC Creo',                                                               'Software Development Tools'),
    ('Quality assurance',                                                      'Software Quality Assurance'),
    ('Responsive design for mobile web development',                           'Web Design and Development'),
    ('Scientific research',                                                     NULL),
    ('Siemens NX',                                                             'Software Development Tools'),
    ('SOA',                                                                    'Web Services'),
    ('Software debug',                                                         'Software Development Tools'),
    ('Software design platforms',                                              'Software Development Tools'),
    ('Software development cycle',                                             'Software Development'),
    ('Software modeling',                                                      'Software Development Tools'),
    ('Software modeling, prototyping',                                         'Software Development Tools'),
    ('Software product management',                                            'Software Development'),
    ('Software project management',                                            'Software Development Tools'),
    ('Software test automation',                                               'Test Automation'),
    ('Software test engineering and test execution',                           'Test Automation'),
    ('Software test environments',                                             'Software Quality Assurance'),
    ('SolidWorks',                                                             'Software Development Tools'),
    ('Source control management',                                              'Version Control'),
    ('Statistical modeling',                                                   'Statistical Modeling'),
    ('Statistics',                                                             'Statistical Modeling'),
    ('System architecture',                                                    'System Design and Implementation'),
    ('Systems management',                                                     'Systems Administration'),
    ('Systems requirement',                                                    'System Design and Implementation'),
    ('Technical architecture design & governance',                             'System Design and Implementation'),
    ('Technical support',                                                      'Technical Support and Services'),
    ('Test tools',                                                             'Test Automation'),
    ('Testing',                                                                'Software Quality Assurance'),
    ('Testing and debugging best practices and tools',                         'Software Quality Assurance'),
    ('Testing methodologies',                                                  'Software Quality Assurance'),
    ('Translate user problems into practical design solutions',                'Web Design and Development'),
    ('Troubleshooting',                                                        'Technical Support and Services'),
    ('Understand and synthesize technology into meaningful human experiences',  'Web Design and Development'),
    ('User acceptance testing',                                                'Test Automation'),
    ('User experience',                                                        'Web Design and Development'),
    ('Validate design solutions',                                              'Web Design and Development'),
    ('Visio',                                                                  'Software Development Tools'),
    ('VMware',                                                                 'Virtualization and Virtual Machines'),
    ('WCF',                                                                    'Web Services'),
    ('White box testing',                                                      'Test Automation')

-- 2) Insert any brand‐new subcategories
INSERT INTO dbo.skill_subcategories (
    skill_subcategory_id,
    subcategory_name,
    subcategory_description
)
SELECT
    NEWID(),
    m.subcategory_name,
    ''  -- blank description
FROM (
         SELECT DISTINCT subcategory_name
         FROM @SkillMap
         WHERE subcategory_name IS NOT NULL
     ) AS m
WHERE NOT EXISTS (
    SELECT 1
    FROM dbo.skill_subcategories sc
    WHERE LOWER(sc.subcategory_name) = LOWER(m.subcategory_name)
);

-- 3) Update each skill’s subcategory_id
UPDATE s
SET s.skill_subcategory_id = sc.skill_subcategory_id
FROM dbo.skills AS s
         INNER JOIN @SkillMap AS m
                    ON LOWER(s.skill_name) = LOWER(m.skill_name)
         INNER JOIN dbo.skill_subcategories AS sc
                    ON LOWER(sc.subcategory_name) = LOWER(m.subcategory_name)
WHERE m.subcategory_name IS NOT NULL
  AND (
    s.skill_subcategory_id IS NULL
        OR s.skill_subcategory_id <> sc.skill_subcategory_id
    );

COMMIT;
