BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[cip] ADD [createdAt] DATETIME NOT NULL CONSTRAINT [cip_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
[updatedAt] DATETIME NOT NULL CONSTRAINT [cip_updatedAt_df] DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE [dbo].[cip_to_socc_map] ADD [createdAt] DATETIME NOT NULL CONSTRAINT [cip_to_socc_map_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
[updatedAt] DATETIME NOT NULL CONSTRAINT [cip_to_socc_map_updatedAt_df] DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE [dbo].[socc] ADD [createdAt] DATETIME NOT NULL CONSTRAINT [socc_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
[updatedAt] DATETIME NOT NULL CONSTRAINT [socc_updatedAt_df] DEFAULT CURRENT_TIMESTAMP;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
